#!/usr/bin/env bash

set -eou pipefail

stage=-1
stop_stage=100

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/voc2007_model_data
#      You can find the files for backbone weights, style of 
#      text, voc 2007 classes
#      You can also download these files form this url:
#      https://zenodo.org/record/3625687#.Ybn7HagzY2w. 
#     
#     - voc_weights_backbone
#       - resnet50-19c8e357.pth
#       - vgg16-397923af.pth
#       - voc_weights_resnet.pth
#       - voc_weights_vgg.pth
#     - semhei.ttf
#     - voc_classes.txt
#       

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le -1 ] && [ $stop_stage -ge -1 ]; then
  log "Stage -1: Download VOC2007 dataset and Unzip"
  # We assume that you have downloaded the VOC2007 dataset, and unzip it.
  # wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
  # wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
  # wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCdevkit_08-Jun-2007.tar
  # tar xvf VOCtrainval_06-Nov-2007.tar
  # tar xvf VOCtest_06-Nov-2007.tar
  # tar xvf VOCdevkit_08-Jun-2007.tar
  
  # Here, we get the VOC2007 dataset directory as follows:
  # - /userhome/data/voc_2007_2012/VOC2007
  #   - Annotations  
  #   - ImageSets  
  #   - JPEGImages  
  #   - SegmentationClass  
  #   - SegmentationObject 
  #   - codes  
  #   - test
fi

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download model data"
  # For this step, you should download some model data files for modeling.
  # You can download them as follows.
  #
  
  [ ! -e $dl_dir/voc2007_model_data ] && mkdir -p $dl_dir/voc2007_model_data

  # Download the model data
  # You should make sure you have installed git-lfs
  # You can install git-lfs as follows:
  # apt-get install git-lfs
  if [! -e $dl_dir/voc2007_model_data ]; then
      git lfs install
      git clone https://huggingface.co/luomingshuang/voc2007_model_data $dl_dir/voc2007_model_data
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare train and val data"
  data_dir=/userhome/data/voc_2007_2012
  out_dir=data/voc2007
  year=2007
  
  mkdir -p $out_dir

  python ./local/voc_annotation.py \
   --data-dir $data_dir \
   --out-dir $out_dir \
   --class-txt $dl_dir/voc2007_model_data/voc_classes.txt \
   --year 2007 \
   --trainval-percent 0.9 \
   --train-percent 0.9 \
   --annotation-mode 0
   
fi