#!/usr/bin/env bash

set -eou pipefail

stage=-1
stop_stage=100

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/mscoco2017
#    - annotations
#    - train2017
#    - val2017
#    - test2017
#
# You can download the dataset from the following url:
# https://github.com/fundamentalvision/Deformable-DETR.git
#       

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le -1 ] && [ $stop_stage -ge -1 ]; then
  log "Stage -1: Download mscoco2017 dataset and Unzip"
  # We assume that you have downloaded the mscoco2017 dataset, and unzip it.
  # wget https://openi.pcl.ac.cn/attachments/93afd342-e8ba-4dd2-bfce-d86046aec359?type=0
  # wget https://openi.pcl.ac.cn/attachments/f019428c-3794-42be-9eb4-f719191a0027?type=0
  # wget https://openi.pcl.ac.cn/attachments/33e8397c-60eb-4050-a44d-f82ffa3e8bc8?type=0
  # wget https://openi.pcl.ac.cn/attachments/d5ba4a08-9aa4-43b9-ab20-52d0aff8edf3?type=1
  # mkdir mscoco2017
  # unzip train2017.zip
  # unzip val2017.zip
  # unzip test2017.zip
  # unzip data.zip
  # mv train2017 mscoco2017
  # mv val2017 mscoco2017
  # mv test2017 mscoco2017
  # mv data/annotations mscoco2017
  
fi

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download model data"
  # For this step, you should download some model data files for modeling.
  # You can download them as follows.
  #
  
  [ ! -e $dl_dir/detr_pretrained_model ] && mkdir -p $dl_dir/detr_pretrained_model

  wget https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth
  # You can use the pretrained model for testing.
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: train, val and eval_metrics"
  # please have a reference for run.sh
fi